candidate_size = -1
checkpoint = "path/to/checkpoint"
dataset = "nell"
debug = false
embed_fn = "complEx_nell.ckpt"
eval_every = 10000
eval_size = 2000
gpu = -1
grad_clip = 5.0
log_every = 50
lr = 5e-5
margin = 2.0
max_epochs = 500000
mode = "append"
name = "TransAM"
neg_rate = 1
parent = ""
pretrain = "ComplEx"
query_size = 100
seed = 1234
test = false
test_in_fit = true
warmup_epochs = 10000
weight_decay = 0.0

[model]
activation_fn = "gelu"
aggr_heads = "keep"
dropout_embed = 0.3
dropout_tr = 0.3
embed_dim = 100
encoder = "attn"
matcher = "single"
max_neighbors = 50
num_heads = 4
num_layers = 3
shot = 5
